INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Can''t Stop the Music', 'Associated Film Distribution', 'Allan Carr', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Cruising', 'Lorimar Productions, United Artists', 'Jerry Weintraub', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'The Formula', 'MGM, United Artists', 'Steve Shagan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Friday the 13th', 'Paramount Pictures', 'Sean S. Cunningham', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'The Nude Bomb', 'Universal Studios', 'Jennings Lang', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'The Jazz Singer', 'Associated Film Distribution', 'Jerry Leider', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Raise the Titanic', 'Associated Film Distribution', 'William Frye', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Saturn 3', 'Associated Film Distribution', 'Stanley Donen', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Windows', 'United Artists', 'Mike Lobell', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1980, 'Xanadu', 'Universal Studios', 'Lawrence Gordon', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1981, 'Mommie Dearest', 'Paramount Pictures', 'Frank Yablans', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1981, 'Endless Love', 'Universal Studios, PolyGram', 'Dyson Lovell', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1981, 'Heaven''s Gate', 'United Artists', 'Joann Carelli', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1981, 'The Legend of the Lone Ranger', 'Universal Studios, Associated Film Distribution', 'Walter Coblenz', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1981, 'Tarzan, the Ape Man', 'MGM, United Artists', 'John Derek', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1982, 'Inchon', 'MGM', 'Mitsuharu Ishii', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1982, 'Annie', 'Columbia Pictures', 'Ray Stark', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1982, 'Butterfly', 'Analysis Film Releasing', 'Matt Cimber', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1982, 'Megaforce', '20th Century Fox', 'Albert S. Ruddy', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1982, 'The Pirate Movie', '20th Century Fox', 'David Joseph', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1983, 'The Lonely Lady', 'Universal Studios', 'Robert R. Weston', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1983, 'Hercules', 'MGM, United Artists, Cannon Films', 'Yoram Globus and Menahem Golan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1983, 'Jaws 3-D', 'Universal Studios', 'Rupert Hitzig', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1983, 'Stroker Ace', 'Warner Bros., Universal Studios', 'Hank Moonjean', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1983, 'Two of a Kind', '20th Century Fox', 'Roger M. Rothstein and Joe Wizan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1984, 'Bolero', 'Cannon Films', 'Bo Derek', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1984, 'Cannonball Run II', 'Warner Bros.', 'Albert S. Ruddy', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1984, 'Rhinestone', '20th Century Fox', 'Marvin Worth and Howard Smith', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1984, 'Sheena', 'Columbia Pictures', 'Paul Aratow', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1984, 'Where the Boys Are ''84', 'TriStar Pictures', 'Allan Carr', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1985, 'Rambo: First Blood Part II', 'Columbia Pictures', 'Buzz Feitshans', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1985, 'Fever Pitch', 'MGM, United Artists', 'Freddie Fields', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1985, 'Revolution', 'Warner Bros.', 'Irwin Winkler', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1985, 'Rocky IV', 'MGM, United Artists', 'Irwin Winkler and Robert Chartoff', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1985, 'year_launch of the Dragon', 'MGM, United Artists', 'Dino De Laurentiis', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1986, 'Howard the Duck', 'Universal Studios', 'Gloria Katz', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1986, 'Under the Cherry Moon', 'Warner Bros.', 'Bob Cavallo, Joe Ruffalo and Steve Fargnoli', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1986, 'Blue City', 'Paramount Pictures', 'William L. Hayward and Walter Hill', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1986, 'Cobra', 'Warner Bros., Cannon Films', 'Yoram Globus and Menahem Golan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1986, 'Shanghai Surprise', 'MGM', 'John Kohn', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1987, 'Leonard Part 6', 'Columbia Pictures', 'Bill Cosby', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1987, 'Ishtar', 'Columbia Pictures', 'Warren Beatty', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1987, 'Jaws: The Revenge', 'Universal Studios', 'Joseph Sargent', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1987, 'Tough Guys Don''t Dance', 'Cannon Films', 'Yoram Globus and Menahem Golan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1987, 'Who''s That Girl', 'Warner Bros.', 'Rosilyn Heller and Bernard Williams', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1988, 'Cocktail', 'Touchstone Pictures', 'Ted Field and Robert W. Cort', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1988, 'Caddyshack II', 'Warner Bros.', 'Neil Canton, Jon Peters and Peter Guber', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1988, 'Hot to Trot', 'Warner Bros.', 'Steve Tisch', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1988, 'Mac and Me', 'Orion Pictures', 'R. J. Louis', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1988, 'Rambo III', 'TriStar Pictures, Carolco Pictures', 'Buzz Feitshans', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1989, 'Star Trek V: The Final Frontier', 'Paramount Pictures', 'Harve Bennett', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1989, 'The Karate Kid Part III', 'Columbia Pictures', 'Jerry Weintraub', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1989, 'Lock Up', 'TriStar Pictures, Carolco Pictures', 'Charles Gordon and Lawrence Gordon', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1989, 'Road House', 'United Artists', 'Joel Silver', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1989, 'Speed Zone', 'Orion Pictures', 'Murray Shostack', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1990, 'The Adventures of Ford Fairlane', '20th Century Fox', 'Steven Perry and Joel Silver', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1990, 'Ghosts Can''t Do It', 'Triumph Releasing', 'Bo Derek', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1990, 'The Bonfire of the Vanities', 'Warner Bros.', 'Brian De Palma', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1990, 'Graffiti Bridge', 'Warner Bros.', 'Randy Phillips and Craig Rice', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1990, 'Rocky V', 'United Artists', 'Robert Chartoff and Irwin Winkler', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1991, 'Hudson Hawk', 'TriStar Pictures', 'Joel Silver', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1991, 'Cool as Ice', 'Universal Studios', 'Carolyn Pfeiffer and Lionel Wingram', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1991, 'Dice Rules', 'Seven Arts Productions', 'Loucas George', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1991, 'Nothing but Trouble', 'Warner Bros.', 'Lester Berman and Robert K. Weiss', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1991, 'Return to the Blue Lagoon', 'Columbia Pictures', 'William A. Graham', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1992, 'Shining Through', '20th Century Fox', 'Carol Baum and Howard Rosenman', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1992, 'The Bodyguard', 'Warner Bros.', 'Kevin Costner, Lawrence Kasdan and Jim Wilson', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1992, 'Christopher Columbus: The Discovery', 'Warner Bros.', 'Alexander Salkind and Ilya Salkind', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1992, 'Final Analysis', '20th Century Fox', 'Paul Junger Witt, Charles Roven and Tony Thomas', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1992, 'Newsies', 'Walt Disney Pictures', 'Michael Finnell', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1993, 'Indecent Proposal', 'Paramount Pictures', 'Sherry Lansing', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1993, 'Body of Evidence', 'MGM, United Artists', 'Dino De Laurentiis', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1993, 'Cliffhanger', 'TriStar Pictures, Carolco Pictures', 'Renny Harlin and Alan Marshall', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1993, 'Last Action Hero', 'Columbia Pictures', 'John McTiernan and Stephen J. Roth', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1993, 'Sliver', 'Paramount Pictures', 'Robert Evans', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1994, 'Color of Night', 'Hollywood Pictures', 'Buzz Feitshans and David Matalon', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1994, 'North', 'Columbia Pictures, Castle Rock Entertainment', 'Rob Reiner and Alan Zweibel', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1994, 'On Deadly Ground', 'Warner Bros.', 'A. Kitman Ho, Julius R. Nasso and Steven Seagal', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1994, 'The Specialist', 'Warner Bros.', 'Jerry Weintraub', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1994, 'Wyatt Earp', 'Warner Bros.', 'Kevin Costner, Lawrence Kasdan and Jim Wilson', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1995, 'Showgirls', 'MGM, United Artists', 'Charles Evans and Alan Marshall', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1995, 'Congo', 'Paramount Pictures', 'Kathleen Kennedy and Sam Mercer', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1995, 'It''s Pat', 'Touchstone Pictures', 'Charles B. Wessler', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1995, 'The Scarlet Letter', 'Hollywood Pictures', 'Roland JoffÃ© and Andrew G. Vajna', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1995, 'Waterworld', 'Universal Studios', 'Kevin Costner, John Davis, Charles Gordon and Lawrence Gordon', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1996, 'Striptease', 'Columbia Pictures, Castle Rock Entertainment', 'Andrew Bergman and Mike Lobell', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1996, 'Barb Wire', 'PolyGram Filmed Entertainment, Gramercy Pictures', 'Todd Moyer, Mike Richardson and Brad Wyman', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1996, 'Ed', 'Universal Studios', 'Rosalie Swedlin', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1996, 'The Island of Dr. Moreau', 'New Line Cinema', 'Edward R. Pressman', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1996, 'The Stupids', 'New Line Cinema, Savoy Pictures', 'Leslie Belzberg', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1997, 'The Postman', 'Warner Bros.', 'Kevin Costner, Steve Tisch and Jim Wilson', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1997, 'Anaconda', 'Columbia Pictures', 'Verna Harrah, Carole Little and Leonard Rabinowitz', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1997, 'Batman & Robin', 'Warner Bros.', 'Peter MacGregor-Scott', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1997, 'Fire Down Below', 'Warner Bros.', 'Julius R. Nasso and Steven Seagal', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1997, 'Speed 2: Cruise Control', '20th Century Fox', 'Jan de Bont, Steve Perry and Michael Peyser', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1998, 'An Alan Smithee Film: Burn Hollywood Burn', 'Hollywood Pictures', 'Ben Myron and Joe Eszterhas', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1998, 'Armageddon', 'Touchstone Pictures', 'Michael Bay and Jerry Bruckheimer', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1998, 'The Avengers', 'Warner Bros.', 'Jerry Weintraub', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1998, 'Godzilla', 'TriStar Pictures', 'Roland Emmerich and Dean Devlin', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1998, 'Spice World', 'Columbia Pictures', 'Uri Fruchtan, Mark L. Rosen and Barnaby Thompson', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1999, 'Wild Wild West', 'Warner Bros.', 'Jon Peters and Barry Sonnenfeld', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1999, 'Big Daddy', 'Columbia Pictures', 'Sidney Ganis and Jack Giarraputo', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1999, 'The Blair Witch Project', 'Artisan Entertainment', 'Robin Cowie and Gregg Hale', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1999, 'The Haunting', 'DreamWorks', 'Susan Arthur, Donna Roth and Colin Wilson', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (1999, 'Star Wars: Episode I â€“ The Phantom Menace', '20th Century Fox', 'Rick McCallum and George Lucas', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2000, 'Battlefield Earth', 'Warner Bros., Franchise Pictures', 'Jonathan D. Krane, Elie Samaha and John Travolta', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2000, 'Book of Shadows: Blair Witch 2', 'Artisan Entertainment', 'Bill Carraro', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2000, 'The Flintstones in Viva Rock Vegas', 'Universal Studios', 'Bruce Cohen', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2000, 'Little Nicky', 'New Line Cinema', 'Jack Giarraputo and Robert Simonds', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2000, 'The Next Best Thing', 'Paramount Pictures', 'Leslie Dixon, Linne Radmin and Tom Rosenberg', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2001, 'Freddy Got Fingered', '20th Century Fox', 'Larry Brezner, Howard Lapides and Lauren Lloyd', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2001, 'Driven', 'Warner Bros., Franchise Pictures', 'Renny Harlin, Elie Samaha and Sylvester Stallone', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2001, 'Glitter', '20th Century Fox, Columbia Pictures', 'Laurence Mark and E. Bennett Walsh', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2001, 'Pearl Harbor', 'Touchstone Pictures', 'Michael Bay and Jerry Bruckheimer', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2001, '3000 Miles to Graceland', 'Warner Bros., Franchise Pictures', 'Demian Lichtenstein, Eric Manes, Elie Samaha, Richard Spero and Andrew Stevens', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2002, 'Swept Away', 'Screen Gems', 'Matthew Vaughn', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2002, 'The Adventures of Pluto Nash', 'Warner Bros.', 'Martin Bregman, Michael Scott Bregman and Louis A. Stroller', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2002, 'Crossroads', 'Paramount Pictures', 'Ann Carli', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2002, 'Pinocchio', 'Miramax Films', 'Gianluigi Braschi, Nicoletta Braschi and Elda Ferri', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2002, 'Star Wars: Episode II â€“ Attack of the Clones', '20th Century Fox', 'Rick McCallum and George Lucas', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2003, 'Gigli', 'Columbia Pictures, Revolution Studios', 'Martin Brest and Casey Silver', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2003, 'The Cat in the Hat', 'Universal Studios, DreamWorks', 'Brian Grazer', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2003, 'Charlie''s Angels: Full Throttle', 'Columbia Pictures', 'Drew Barrymore, Leonard Goldberg and Nancy Juvonen', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2003, 'From Justin to Kelly', '20th Century Fox', 'John Steven Agoglia', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2003, 'The Real Cancun', 'New Line Cinema', 'Mary-Ellis Bunim, Jonathan Murray, Jamie Schutz and Rick de Oliveira', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2004, 'Catwoman', 'Warner Bros.', 'Denise Di Novi and Edward McDonnell', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2004, 'Alexander', 'Warner Bros.', 'Moritz Borman, Jon Kilik, Thomas Schuhly and Iain Smith', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2004, 'Superbabies: Baby Geniuses 2', 'Triumph Films', 'Steven Paul', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2004, 'Surviving Christmas', 'DreamWorks', 'Betty Thomas and Jenno Topping', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2004, 'White Chicks', 'Columbia Pictures, Revolution Studios', 'Rick Alvarez, Lee R. Mayes, Keenen Ivory Wayans, Marlon Wayans and Shawn Wayans', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2005, 'Dirty Love', 'First Look Pictures', 'John Mallory Asher, BJ Davis, Rod Hamilton, Kimberley Kates, Michael Manasseri, Jenny McCarthy and Trent Walford', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2005, 'Deuce Bigalow: European Gigolo', 'Columbia Pictures', 'Adam Sandler and Rob Schneider', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2005, 'The Dukes of Hazzard', 'Warner Bros., Village Roadshow', 'Bill Gerber', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2005, 'House of Wax', 'Warner Bros., Village Roadshow', 'Susan Levin, Joel Silver and Robert Zemeckis', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2005, 'Son of the Mask', 'New Line Cinema', 'Erica Huggins and Scott Kroopf', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2006, 'Basic Instinct 2', 'MGM, C2 Pictures', 'Mario Kassar, Joel B. Michaels and Andrew G. Vajna', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2006, 'BloodRayne', 'Romar Entertainment', 'Uwe Boll, Dan Clarke and Wolfgang Herrold', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2006, 'Lady in the Water', 'Warner Bros.', 'Sam Mercer, Jose L. Rodriguez and M. Night Shyamalan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2006, 'Little Man', 'Columbia Pictures, Revolution Studios', 'Rick Alvares, Lee Mays, Marlon Wayans and Shawn Wayans', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2006, 'The Wicker Man', 'Warner Bros.', 'Nicolas Cage, Randall Emmett, Norm Golightly, Avi Lerner and Joanne Sellar', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2007, 'I Know Who Killed Me', 'TriStar Pictures', 'David Grace and Frank Mancuso Jr.', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2007, 'Bratz', 'Lionsgate', 'Avi Arad, Isaac Larian and Steven Paul', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2007, 'Daddy Day Camp', 'TriStar Pictures, Revolution Studios', 'Matt Berenson, John Davis and Wyck Godfrey', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2007, 'I Now Pronounce You Chuck & Larry', 'Universal Studios', 'Adam Sandler and Tom Shadyac', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2007, 'Norbit', 'DreamWorks', 'John Davis, Eddie Murphy and Michael Tollin', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2008, 'The Love Guru', 'Paramount Pictures', 'Gary Barber, Michael DeLuca and Mike Myers', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2008, 'Disaster Movie and Meet the Spartans', 'Lionsgate, 20th Century Fox', 'Jason Friedberg, Peter Safran and Aaron Seltzer', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2008, 'The Happening', '20th Century Fox', 'Barry Mendel, Sam Mercer and M. Night Shyamalan', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2008, 'The Hottie & the Nottie', 'Regent Releasing', 'Hadeel Reda', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2008, 'In the Name of the King', 'Boll KG, Brightlight Pictures', 'Uwe Boll, Dan Clarke, Wolfgang Herrold and Shawn Williamson', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2009, 'Transformers: Revenge of the Fallen', 'Paramount Pictures, DreamWorks, Hasbro', 'Lorenzo di Bonaventura, Ian Bryce, Tom DeSanto and Don Murphy', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2009, 'All About Steve', '20th Century Fox', 'Sandra Bullock and Mary McLaglen', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2009, 'G.I. Joe: The Rise of Cobra', 'Paramount Pictures, Hasbro', 'Lorenzo di Bonaventura, Bob Ducsay and Brian Goldner', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2009, 'Land of the Lost', 'Universal Studios', 'Sid and Marty Krofft and Jimmy Miller', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2009, 'Old Dogs', 'Walt Disney Pictures', 'Peter Abrams, Robert Levy and Andrew Panay', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2010, 'The Last Airbender', 'Paramount Pictures, Nickelodeon Movies', 'Frank Marshall, Kathleen Kennedy, Sam Mercer and M. Night Shyamalan', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2010, 'The Bounty Hunter', 'Columbia Pictures', 'Neal H. Moritz', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2010, 'Sex and the City 2', 'New Line Cinema, HBO Films, Village Roadshow Pictures', 'Michael Patrick King, John Melfi, Sarah Jessica Parker and Darren Star', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2010, 'The Twilight Saga: Eclipse', 'Summit Entertainment', 'Wyck Godfrey and Karen Rosenfelt', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2010, 'Vampires Suck', '20th Century Fox', 'Jason Friedberg, Peter Safran and Aaron Seltzer', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2011, 'Jack and Jill', 'Columbia Pictures', 'Todd Garner, Jack Giarraputo and Adam Sandler', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2011, 'Bucky Larson: Born to Be a Star', 'Columbia Pictures', 'Barry Bernardi, Allen Covert, David Dorfman and Jack Giarraputo', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2011, 'New year_launch''s Eve', 'Warner Bros., New Line Cinema', 'Mike Karz, Garry Marshall and Wayne Allan Rice', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2011, 'Transformers: Dark of the Moon', 'Paramount Pictures', 'Lorenzo di Bonaventura, Ian Bryce, Tom DeSanto and Don Murphy', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2011, 'The Twilight Saga: Breaking Dawn â€“ Part 1', 'Summit Entertainment', 'Wyck Godfrey, Stephenie Meyer and Karen Rosenfelt', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2012, 'The Twilight Saga: Breaking Dawn â€“ Part 2', 'Summit Entertainment', 'Wyck Godfrey, Stephenie Meyer and Karen Rosenfelt', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2012, 'Battleship', 'Universal Studios', 'Sarah Aubrey, Peter Berg, Brian Goldner, Duncan Henderson, Bennett Schneir and Scott Stuber', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2012, 'The Oogieloves in the Big Balloon Adventure', 'Lionsgate Films, Romar Entertainment, Kenn Viselman Presents', 'Gayle Dickie, Kenn Viselman', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2012, 'That''s My Boy', 'Columbia Pictures', 'Allen Covert, Jack Giarraputo, Heather Parry and Adam Sandler', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2012, 'A Thousand Words', 'Paramount Pictures, DreamWorks', 'Nicolas Cage, Alain Chabat, Stephanie Danan, Norman Golightly, Brian Robbinsand Sharla Sumpter Bridgett', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2013, 'Movie 43', 'Relativity Media', 'Peter Farrelly, Ryan Kavanaugh, John Penotti and Charles B. Wessler', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2013, 'After Earth', 'Columbia Pictures', 'James Lassiter, Caleeb Pinkett, Jada Pinkett Smith, M. Night Shyamalan, Will Smith and Jaden Smith', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2013, 'Grown Ups 2', 'Columbia Pictures', 'Jack Giarraputo and Adam Sandler', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2013, 'The Lone Ranger', 'Walt Disney Pictures', 'Jerry Bruckheimer and Gore Verbinski', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2013, 'A Madea Christmas', 'Lionsgate', 'Ozzie Areu, Matt Moore and Tyler Perry', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2014, 'Saving Christmas', 'Samuel Goldwyn Films', 'Darren Doane, Raphi Henley, Amanda Rosser and David Shannon', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2014, 'Left Behind', 'Freestyle Releasing, Entertainment One', 'Michael Walker and Paul LaLonde', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2014, 'The Legend of Hercules', 'Summit Entertainment', 'Boaz Davidson, Renny Harlin, Danny Lerner and Les Weldon', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2014, 'Teenage Mutant Ninja Turtles', 'Paramount Pictures, Nickelodeon Movies, Platinum Dunes', 'Michael Bay, Ian Bryce, Andrew Form, Bradley Fuller, Scott Mednick and Galen Walker', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2014, 'Transformers: Age of Extinction', 'Paramount Pictures', 'Ian Bryce, Tom DeSanto, Lorenzo di Bonaventura and Don Murphy', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2015, 'Fantastic Four', '20th Century Fox', 'Simon Kinberg, Matthew Vaughn, Hutch Parker, Robert Kulzer and Gregory Goodman', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2015, 'Fifty Shades of Grey', 'Universal Pictures, Focus Features', 'Michael De Luca, Dana Brunetti and E. L. James', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2015, 'Jupiter Ascending', 'Warner Bros.', 'Grant Hill and The Wachowskis', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2015, 'Paul Blart: Mall Cop 2', 'Columbia Pictures', 'Todd Garner, Kevin James and Adam Sandler', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2015, 'Pixels', 'Columbia Pictures', 'Adam Sandler, Chris Columbus, Mark Radcliffe and Allen Covert', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2016, 'Hillary''s America: The Secret History of the Democratic Party', 'Quality Flix', 'Gerald R. Molen', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2016, 'Batman v Superman: Dawn of Justice', 'Warner Bros.', 'Charles Roven and Deborah Snyder', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2016, 'Dirty Grandpa', 'Lionsgate', 'Bill Block, Michael Simkin, Jason Barrett and Barry Josephson', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2016, 'Gods of Egypt', 'Summit Entertainment', 'Basil Iwanyk and Alex Proyas', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2016, 'Independence Day: Resurgence', '20th Century Fox', 'Dean Devlin, Harald Kloser and Roland Emmerich', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2016, 'Zoolander 2', 'Paramount Pictures', 'Stuart Cornfeld, Scott Rudin, Ben Stiller and Clayton Townsend', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2017, 'The Emoji Movie', 'Columbia Pictures', 'Michelle Raimo Kouyate', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2017, 'Baywatch', 'Paramount Pictures', 'Ivan Reitman, Michael Berk, Douglas Schwartz, Gregory J. Bonann and Beau Flynn', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2017, 'Fifty Shades Darker', 'Universal Pictures', 'Michael De Luca, E. L. James, Dana Brunetti and Marcus Viscidi', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2017, 'The Mummy', 'Universal Pictures', 'Alex Kurtzman, Chris Morgan, Sean Daniel and Sarah Bradshaw', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2017, 'Transformers: The Last Knight', 'Paramount Pictures', 'Don Murphy, Tom DeSanto, Lorenzo di Bonaventura and Ian Bryce', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2018, 'Holmes & Watson', 'Columbia Pictures', 'Will Ferrell, Adam McKay, Jimmy Miller and Clayton Townsend', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2018, 'Gotti', 'Vertical Entertainment', 'Randall Emmett, Marc Fiore, Michael Froch and George Furla', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2018, 'The Happytime Murders', 'STX', 'Ben Falcone, Jeffrey Hayes, Brian Henson and Melissa McCarthy', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2018, 'Robin Hood', 'Summit Entertainment', 'Jennifer Davisson and Leonardo DiCaprio', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2018, 'Winchester', 'Lionsgate', 'Tim McGahan and Brett Tomberlin', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2019, 'Cats', 'Universal Pictures', 'Debra Hayward, Tim Bevan, Eric Fellner, and Tom Hooper', true);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2019, 'The Fanatic', 'Quiver Distribution', 'Daniel Grodnik, Oscar Generale, and Bill Kenwright', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2019, 'The Haunting of Sharon Tate', 'Saban Films', 'Lucas Jarach, Daniel Farrands, and Eric Brenner', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2019, 'A Madea Family Funeral', 'Lionsgate', 'Ozzie Areu, Will Areu, and Mark E. Swinton', false);
INSERT INTO movie (year_launch, title, studios, producers, winner) VALUES (2019, 'Rambo: Last Blood', 'Lionsgate', 'Avi Lerner, Kevin King Templeton, Yariv Lerner, and Les Weldon', false);